### ISSUE TITLE
folder separator  issue on windows.

### ISSUE THREAD

**Issue by coolmax2000** [gangtao/dataplay2#1]
running server on windows when select data, will report 404 file not found issue like below.
127.0.0.1 - - [25/Mar/2016 16:30:14] "GET /data/data/Cars HTTP/1.1" 404 -

Fixing:
Change main.py line 39:
flist = [f.replace('./data/', '').replace('.csv', '')
to:
flist = [f.replace('./data/', '').replace('./data\\', '').replace('.csv', '')

**Comment by gangtao** [comment]
I was working on Mac, will check this,  Thanks!

**Comment by gangtao** [comment]
this issue should have been fixed by the pull request https://github.com/gangtao/dataplay2/pull/3 which has been merged.
