### ISSUE TITLE
docker运行问题反馈！

### ISSUE THREAD

**Issue by starjason** [gangtao/dataplay2#4]
好不容易构建成功，好家伙足足有2.734 GB！
`docker run -d -p 5000:5000 dataplay2 
7c7acf68c8f57d40b9edf92017d1324a40cd14ba6e0fb127e2438281f502135a
docker: Error response from daemon: Container command '/start.sh' not found or does not exist..`

于是尝试修改Dockerfile中的
`COPY /start.sh /` 修改为 `COPY ./start.sh /`
重新构建后，运行正常！
请知悉！

**Comment by gangtao** [comment]
谢谢反馈！

**Comment by gangtao** [comment]
fixed!
